### ISSUE TITLE
Function geometry output is not transformed to SRID 4326

### ISSUE THREAD

**Issue by smnorris** [CrunchyData/pg_featureserv#114]
Running latest (v1.3), this function request returns BC Albers coordinates that do not get automatically translated into EPSG:4326:
https://features.hillcrestgeo.ca/fwa/functions/postgisftw.fwa_locatealonginterval/items.json?blue_line_key=359572348&start_measure=1597489&interval_length=1000&end_measure=1706733

With v1.2, requests to the same database and same function transform data to 4326 and display without issue (using the same pg_featureserv config).

Adding some extra type casts to the query in my function does not seem to help.

Is this expected behaviour, a bug, or am I missing something new that is required in the config or db setup?

Example function: https://github.com/smnorris/fwapg/blob/main/sql/functions/FWA_LocateAlongInterval.sql

**Comment by dr-jts** [comment]
This is a regression, caused by [this change](https://github.com/CrunchyData/pg_featureserv/commit/739e2dcbb7ecd11a0f5e3587908ca85cd667867b#diff-aa80d5452450d22516fb2cb8efca9416480fb18aa49061019b61437bf016de60R330).

Looks like the fix is easy, so I'll merge that and then let you know so you can test.

**Comment by dr-jts** [comment]
@smnorris can you test this fix?

**Comment by smnorris** [comment]
@dr-jts Looks good to me, thanks for the quick fix.
