### ISSUE TITLE
Malware in zipfile

### ISSUE THREAD

**Issue by PeterSteen01** [CrunchyData/pg_featureserv#45]
Hi guys. Wanted to try out the feature server and downed the windows version. Got a report from my Symantec Virus scanner that the file contains some malware:

![image](https://user-images.githubusercontent.com/32326872/81147301-4aaf3580-8f7a-11ea-92c6-a011c41af098.png)

**Comment by PeterSteen01** [comment]
Looking a little into this it seems to be a false positive thrown by symantect because it does not recognize the exe file. Maybe you should get it added to Symantecs whitelist ?

**Comment by pramsey** [comment]
Yeah, I can see why some firewalls might not like "exe in a zip file", but I also can't see any obvious way to avoid it, since the whole point is... to ship an exe in a zip file. Like, that's the simplest possible way to make the functionality available. I cannot imagine how I would ever get on a whitelist, perhaps it's something you'd like to research.
