### ISSUE TITLE
API when using Proxy and UrlBase

### ISSUE THREAD

**Issue by reyemtm** [CrunchyData/pg_featureserv#55]
I am using a proxy for featureserv which works great with the UrlBase set to the proxy path. Everything works except the openapi schema page. The openapi schema uses the root url of the request and not the UrlBase as defined in the config. For example, the `/api` query uses  `https://311.coz.org` + `/api`, not the UrlBase which would be `https://311.coz.org/api/v1/feature-server` + `/api`. I am not sure if this is by design or a bug.

The server in question is https://311.coz.org/api/v1/feature-server/api.html.

Thanks for the awesome software! It's currently powering our public municipal GIS web maps.

**Comment by dr-jts** [comment]
That's a bug.  Will work on it ASAP.

**Comment by dr-jts** [comment]
Hopefully fixed by https://github.com/CrunchyData/pg_featureserv/commit/53818bafba2c14ce6f03c2f2f490dd99ecea7182. 

@reyemtm Are you able to test and report back?

**Comment by reyemtm** [comment]
Yes I can do that. Will attempt this tomorrow.

**Comment by reyemtm** [comment]
The update seems to have fixed the issue.

I did receive this error message on the api route, but it does return a valid response so not sure what this means.

```
Resolver error at paths./api/v1/feature-server/api.get.responses.200.$ref
Could not resolve reference: Failed to fetch
```

**Comment by dr-jts** [comment]
How did you generate that error?  Is it persistent?

Otherwise, looks like this issue is resolved?

**Comment by reyemtm** [comment]
I get it when I click the second accordion in the api schema page. 

https://311.coz.org/api/v1/feature-server/api.html#/default/getAPI

**Comment by dr-jts** [comment]
That error is reported because the service is running under HTTPS but the API page is requesting an HTTP resource:
![image](https://user-images.githubusercontent.com/3529053/101194255-990cdb80-3612-11eb-82e5-dfed94efa7e4.png)

Not sure why that is. It may be an issue with the Swagger UI lib the API HTML page is using.  

Best to close this issue, and open another one if you are really concerned about this (although not sure there's much I can do).
