### ISSUE TITLE
BBOX in API Schema is not working properly.

### ISSUE THREAD

**Issue by reyemtm** [CrunchyData/pg_featureserv#60]
When the bbox query is not clicked and the route ``/api/v1/feature-server/collections/{collectionId}/items`` is tried, no features are returned. The bbox query does work on the preview page, it is just that the default bounds is incorrect on the api schema page. There is no extent filled out on the collection page, so this could be part of the issue.

https://311.coz.org/api/v1/feature-server/collections/public.adm_census_tracks/items.json?limit=2&bbox=-120%2C30%2C-100%2C49

**Comment by dr-jts** [comment]
Yes, there is a current limitation that causes the table extent to not be populated.

However, I think the reason that query returns an empty result is because the bbox is outside the range of the data.  The following query with a larger bbox returns data:

https://311.coz.org/api/v1/feature-server/collections/public.adm_census_tracks/items.json?limit=2&bbox=-120%2C30%2C-80%2C49

**Comment by dr-jts** [comment]
`master` now contains a fix that populates the table extent in the `collection/name` response.
