### ISSUE TITLE
pg_featureserv and QGIS

### ISSUE THREAD

**Issue by sfkeller** [CrunchyData/pg_featureserv#63]
Enhancement proposal: 
Can pg_featureserv be configured to work with QGIS WMS/OGC API Features connection? 
Goal is for testing and demo purposes and to integrate pg_featureserv and QGIS in a microservice architecture. 
First attempts by active QGIS devs. seem to be unsuccessful so far: https://lists.osgeo.org/pipermail/qgis-user/2020-November/047208.html . /cc @rduivenvoorde

**Comment by dr-jts** [comment]
It would be great to have pg_featureserv work with QGIS.  But as far as I know pg_featureserv is correctly supporting the OAPIF protocol.  QGIS fails when trying to request the top-level page from the service.  It's not clear to me why QGIS is unable to do this.  It might be because it is not setting the `Accept` header to indicate that it wants a JSON response.

It might require working with a QGIS developer to sort this out on both ends.

**Comment by dr-jts** [comment]
Update on this:
* It turns out that the pg_featureserv landing page JSON was missing a couple of the mandatory OAPIF resource links (`service-desc` and `conformance`).  Once these are added, QGIS is able to list the feature collections in the service.  This fix will be committed soon.
* However, QGIS is unable to request the metadata for collections.  I think this is because it is emitting the collection request as `http://localhost:9000/collections.json/ne.us_state`.  This is clearly malformed - note that the format extension `.json` is not at the end of the URL, as it should be.  This is a problem that QGIS should fix.

**Comment by dr-jts** [comment]
@sfkeller are you in touch with QGIS devs to help get the format specifier issue sorted out?

**Comment by dr-jts** [comment]
Update: The malformed collection URL is because `pg_featureserv` is emitting the format specifier `.json` in the links in JSON documents.  This probably needs to be changed so that links to JSON requests don't include the format specifier, since this can be assumed.  Working on this.

When this is changed, QGIS is able to load layers from `pg_featureserv`!

**Comment by dr-jts** [comment]
This should be fixed now.

@sfkeller are you able to try out the code in the repo?

**Comment by sfkeller** [comment]
Yes, I'll involve an assistant of mine (exam session here :-( ). Give me some time this week.

**Comment by rduivenvoorde** [comment]
@dr-jts can I grab 'latest build'? Or do I have to compile myself to test your fix?

**Comment by rduivenvoorde** [comment]
@dr-jts is there anything you think should be fixed/changed on the QGIS end to stay as much to 'standards' as possible?

**Comment by dr-jts** [comment]
> @dr-jts is there anything you think should be fixed/changed on the QGIS end to stay as much to 'standards' as possible?

Not for the changes I made - they were because `pg_featureserv` wasn't quite following the standard.  So far I haven't seen anything else wrong with the QGIS client.

One thing I don't understand is whether QGIS can add a data filter to the query?  I have tried using the Build Query dialog, but it doesn't seem to add anything to the request.

> Another question: is it possible to page through data?

I think that's only partly implemented in `pg_featureserv`.  Does QGIS support this?  If so I can try and see if I can get it working.

**Comment by rduivenvoorde** [comment]
I'm not so familiar with the code intricities, but... 

I also was not able to use some kind of filtering (it even freezes my QGIS (although I use a pretty heavy point db: 9.000.000 adresses)...

Older WFS providers did use paging, but I cannot make this work here yet. 
I will try if I use the QGISserver endpoint if the client behaves differently, and I will ask on the mailing list.
