### ISSUE TITLE
http: panic serving while serving joined table

### ISSUE THREAD

**Issue by HardRock4Life** [CrunchyData/pg_featureserv#77]
Hello!

I'm trying to provide data from table, which if formed from two joined tables. This gives me this error:

```
http: panic serving [::1]:50953: interface conversion: interface {} is nil, not string
goroutine 142 [running]:
net/http.(*conn).serve.func1()
        /home/travis/.gimme/versions/go/src/net/http/server.go:1821 +0xb9
panic({0x147bb80, 0xc000285a70})
        /home/travis/.gimme/versions/go/src/runtime/panic.go:1047 +0x266
net/http.(*timeoutHandler).ServeHTTP(0xc000166440, {0x15aa218, 0xc000250000}, 0xc00009c200)
        /home/travis/.gimme/versions/go/src/net/http/server.go:3319 +0x893
net/http.serverHandler.ServeHTTP({0xc0002840c0}, {0x15aa218, 0xc000250000}, 0x6)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2885 +0x8e
net/http.(*conn).serve(0xc0001061e0, {0x15add80, 0xc00020a150})
        /home/travis/.gimme/versions/go/src/net/http/server.go:1949 +0xb08
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go/src/net/http/server.go:3011 +0x4e8
```

The DDL for the view is the following:

``` 
CREATE OR REPLACE VIEW public.v_get_graven_info
AS SELECT g.grafcode,
    gl.ol_voornamen,
    gl.ol_tussenvoegsels,
    gl.ol_naam,
    gl.ol_geboortedatum,
    gl.ol_overlijdensdatum,
    g.geom
   FROM gravenlijst gl
     LEFT JOIN graven g 
        ON concat(gl.bp_code, gl.g_grafcode) = g.grafcode::text 
        OR concat("substring"(gl.bp_code::text, 2, 3), gl.g_grafcode) = g.grafcode::text;
```

What is the possible solution for it? Is it something to do with the ON operator?

**Comment by dr-jts** [comment]
This might be happening because a value in the query result is NULL, and isn't being handled correctly by `pg_featureserv`.  In particular, there was a recent change https://github.com/CrunchyData/pg_featureserv/commit/0b139639a2c8278a727cb67e5497a1bdc697a2e1 which fixed the handling of NULL geometry values.

Are you able to build and test the current codebase?  This might fix the problem.  If not, report back here and we can try and identify if there is another bug of this sort.

**Comment by HardRock4Life** [comment]
Yes, I do have some NULL values in the result query. I've downloaded an update project and it all worked.
Thank you!
